source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'access_token', path: '../..'
gem 'activerecord', require: 'active_record'
gem 'sqlite3'
gem 'bcrypt'
gem 'pry-meta'
gem 'redis'
