source "https://rubygems.org"

gem "rails", "4.2.1"
gem "sqlite3"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "bcrypt", "~> 3.1.7"
gem "access_token", path: "../.."
gem "redis"

group :development do
  gem "pry-meta"
end
